### ISSUE TITLE
Idea: Show Faction & Level in profile

### ISSUE THREAD

**Issue by Lycanium-Z** [HoeenCoder/Wavelength#18]
It kinda goes without saying

**Comment by HoeenCoder** [comment]
Profile refactor pending, will take this into account

**Comment by DeathlyPlays** [comment]
Exp Level as well

**Comment by HoeenCoder** [comment]
Feel free to do this anyone who wants to

**Comment by DeathlyPlays** [comment]
Well the Exp portion is added @HoeenCoder
