### ISSUE TITLE
Update Super Staff Bros.

### ISSUE THREAD

**Issue by Lycanium-Z** [HoeenCoder/Wavelength#26]
Main TODO:

- [x] Remove former auth for SG
- [x] Update Ranks

- [x] Import Tsunami's Auth

- [x] Add  wgc (Nothing i can do rn so i just left a message on the txt file)

- [x] New Descriptions

----
Also if thou must, This is probably a good time to update any staffmons if you feel like it!

**Comment by DeathlyPlays** [comment]
We need to know who the auth are first though @Lycanium-Z

**Comment by HoeenCoder** [comment]
@Lycanium-Z hold on this for a bit

**Comment by Lycanium-Z** [comment]
Alright @HoeenCoder

**Comment by HoeenCoder** [comment]
your cleared to start this
