### ISSUE TITLE
SGgame bug master list

### ISSUE THREAD

**Issue by Lycanium-Z** [HoeenCoder/Wavelength#48]
Since there isnt really one ill just be the first to do so!

- [x] Clicking a pokeball if there is no mons on your side of the field results in the game freezing

- [x] move learning on evolution doesnt work

- [x] Whenever a mon levels up in the middle of an SGgame battle its stats are buffed uncontrollably

- [x] %Arrays: if a mon levels up mid match it stops gaining exp and doesnt level midmatch || %Arrays: but it does level outside the match

**Comment by Arrays-Arr** [comment]
4th issue is fixed. 1-3's status undetermined

**Comment by wgc-coder** [comment]
Can somebody explain what the "Move learning on evolution doesn't work" issue entails.

**Comment by wgc-coder** [comment]
@Lycanium-Z

**Comment by Lycanium-Z** [comment]
@wgc-coder some moves that pokemon learn on evolution do not trigger Like Silvally and Multi attack.


If type null evolves it should learn multi attack but it does not

**Comment by wgc-coder** [comment]
When looking in pokedex.js only some of these pokemon have evo moves. I think part of the problem there is that they just need someone to do data-entry.

**Comment by Lycanium-Z** [comment]
yeah

**Comment by HoeenCoder** [comment]
Its being worked on, all issues but that listed are fixed

**Comment by DeathlyPlays** [comment]
To-Do List:
- [ ] Exp Share
- [ ] Better Battle AI

**Comment by DeathlyPlays** [comment]
To-Do List:
- [ ] Exp Share
- [ ] Better Battle AI

**Comment by DeathlyPlays** [comment]
I forget some of the things that I should add to that list but @HoeenCoder feel free to edit it as need be

**Comment by HoeenCoder** [comment]
Deleted DeathlyPlays comment because this is for bugs, not feature requests.

Alpha 1.0 is done, only bug fixes are accepted. I'll be opening 2.0 for requests very soon

**Comment by HoeenCoder** [comment]
All fixed
