### ISSUE TITLE
Battles randomly Crash

### ISSUE THREAD

**Issue by Lycanium-Z** [HoeenCoder/Wavelength#66]

**Comment by HoeenCoder** [comment]
Details please, I cant do anything with an equivilant of "stuff is broken please fix"

**Comment by Lycanium-Z** [comment]
Oh sorry @Hoeenhero

When battles load only one user is shown and the other user is null iirc. I think it has to do with Sggame because i haven’t seen this anywhere else

**Comment by Lycanium-Z** [comment]
Here’s a replay detailing what i mean: http://replay.pokemonshowdown.com/wavelength-gen7superstaffbros-10349

**Comment by Lycanium-Z** [comment]
Issue should be fixed with the floette Bug Patch

**Comment by HoeenCoder** [comment]
Id like to find the source of this, since its not supposed be calling SGgame functions outside of SGgame formats.

**Comment by Lycanium-Z** [comment]
Hey remember when floette crashed battles outside of sggame? Now flabebe is doing it :^(

**Comment by HoeenCoder** [comment]
Fixed in #115
