### ISSUE TITLE
SGgame - USUM Pokemon Catch Rates & Base EXP values

### ISSUE THREAD

**Issue by HoeenCoder** [HoeenCoder/Wavelength#68]
Catch rates/ Base EXP values currently aren't avaliable for the new USUM pokemon.
I've set temporary rates & values for them atm, but true data is wanted ASAP.

**Comment by C733937** [comment]
Dusk Lycanroc: Exactly the same as the other Lycanroc
Dusk Mane Necrozma: Seems to be the same as Necrozma except EVs are 3 in attack
Dawn Wings Necrozma: Seems to be the same as Necrozma except EVs are 3 in special attack
Ultra Necrozma: Seems to be the same as Necrozma except EVs are 1 in attack, 1 in special attack, and 1 in speed
Poipole: Catch Rate 45, Base EXP 189, Leveling Rate Slow, EVs 1 in speed
Naganadel: Catch Rate 45, Base EXP 243, Leveling Rate Slow, EVs 3 in special attack
Stakataka: Catch Rate 30, Base EXP 257, Leveling Rate Slow EVs 3 in defense
Blacephelon: Catch Rate 30, Base EXP 257, Leveling Rate Slow, EVs 3 in special attack
Zeraora: Catch Rate 3, Base EXP 270, Leveling Rate Slow, EVs 3 in speed

**Comment by HoeenCoder** [comment]
Wheres the source for this infomation?

**Comment by C733937** [comment]
Bulbapedia

**Comment by DeathlyPlays** [comment]
Will do
